import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { getChartsData } from '../../api/chartsApi'
import rawData from '../../data/data.json'
// import { getUsersStats } from '../../api/firebase'
import initFirebaseApi from '../../api/chartsUpdates'
import homeworkData from '../../data/tasks_to_homeworks_nov.json'
import taskMetadata from '../../data/task_to_level_flat_nov.json'
import { debugErrorMap } from '@firebase/auth'

/* convert to task_to_level_flat
const pData = data.flatMap(el => {
  return el.questionIdList.map(q => ({[q]: el.level}))
})
let reardyData = {}
undefined
pData.forEach(d => {
  reardyData[Object.keys(d)[0]] = Object.values(d)[0]
}) 
*/

const initialState = {
  // firebase,
  code: '',
  status: 'idle',
  filters: {
    homework: 'all',
    type: 'students', // students or tasks
  },
  rawData,
  homeworks: homeworkData,
  taskMetadata: taskMetadata,
  fireInstance: null,
}

// console.log('store ', initialState)
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(fetchCartsData(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchChartsData = createAsyncThunk(
  'charts/fetchData',
  async (amount) => {
    // debugger
    // const response = await getChartsData(amount)
    await instance.getUsersStats()
    console.log('resu ', result)
    // The value we return becomes the `fulfilled` action payload
    return result
  }
)

export const initialize = createAsyncThunk('charts/initialize', async () => {
  // debugger
  // const response = await getChartsData(amount)
  const instance = await initFirebaseApi()
  return instance
})

export const updateRealTimeData = createAsyncThunk(
  'charts/updateRealtime',
  async (data) => {
    console.log('updateRealTime ', data)
    return data
  }
)

export const chartSlice = createSlice({
  name: 'charts',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    setCode: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.code = action.payload
    },
    setData: (state, action) => {
      state.rawData = action.payload
    },
    setFilters: (state, action) => {
      state.filters = action.payload
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(initialize.fulfilled, (state, action) => {
        console.log('initialize ', action)
        state.fireInstance = action.payload
      })
      .addCase(fetchChartsData.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(fetchChartsData.fulfilled, (state, action) => {
        state.status = 'idle'
        state.rawData = action.payload
      })
      .addCase(updateRealTimeData.fulfilled, (state, action) => {
        console.log('update!!11!!', action)
      })
  },
})

export const { setCode, setFilters, setData } = chartSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.charts.value)`
export const selectCode = (state) => state.charts.code
export const selectFilters = (state) => state.charts.filters
export const selectRawGraphData = (state) => state.charts.rawData
export const selectHomeworks = (state) => state.charts.homeworks
export const selectTaskMetadata = (state) => state.charts.taskMetadata

export default chartSlice.reducer
